### ISSUE TITLE
Gap at bottom of password/username generation

### ISSUE THREAD

**Issue by The-Ducktor** [AChep/keyguard-app#27]
At the bottom of the password/username generator popup it there is a gap when you. Scroll all the way down there's no rounding so it doesn't look intentional

![Screenshot_20231017-172132.png](https://github.com/AChep/keyguard-app/assets/130664593/d41f3637-06c7-407b-9411-b72ab7ad31e8)

**Comment by AChep** [comment]
Should be fixed in the next build.

**Comment by The-Ducktor** [comment]
Issue is partially solved it no longer stays with a gap but you can still scroll up were you can see a gap before it pushes the menu back Into place
Along with the little gesture bar in the bottom not being filled when scrolled up
https://github.com/AChep/keyguard-app/assets/130664593/eecb0e90-e56e-400a-af3c-f35aa2403702

**Comment by tmsjngx0** [comment]
**Session handoff** — `ft` receipt, published by the Stop gate.

작업: #27 Diagnose the still-spinning Keyguard desktop app after syncing stella Pi providers

## 다음 단계

- [ ] Continue from the resolved duplicate-cleanup decisions by wiring the existing AutoMerge tool to the local persisted vault data path, then run report mode before any apply mode.

## 답이 필요한 것

- The targeted duplicate desktopTest did not complete after the rebase because Gradle failed while rustup downloaded rustc for util:crypto:verifyNativeCryptoDesktopRustTarget; this is an environment/toolchain download failure, not a Kotlin test failure.

브랜치 `local/mac-gui-build-notes` · 세션 `019ff3cf`
