### ISSUE TITLE
MacOS framerate drops

### ISSUE THREAD

**Issue by zeroSal** [AChep/keyguard-app#606]
MacBook Pro 14'' Late 2023
Apple Silicon M3 Pro
18 GB of RAM
MacOS Sonoma 14.6.1

The app is laggy, animations sometimes stucks.

**Comment by UsamaKarim** [comment]
I second this, the app feels so much laggy on Apple Silicon,
I see this app is using rosetta 2 to translate the code.
Is there a way to run this app natively?

**Comment by zeroSal** [comment]
@UsamaKarim nice flair ;)
Just built it using the Liberica JDK 17 for the `arm64` architecture and the issue is fixed.
Submitted a new pull request #625 to @AChep.

**Comment by AChep** [comment]
This is not fully solved, the `brew` cask is still pointing to the x64 binaries. The proper way would be to create an universal image, but that is not yet supported by the Compose for Desktop.

**Comment by AChep** [comment]
Looking at the https://github.com/Homebrew/homebrew-cask/blob/master/Casks/f/flutter.rb it should be possible to specify the arch tho.
